### ISSUE TITLE
Add QC school pages

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#109]
There are two "new" web pages.

* Highlights - Public and Private School Systems: [EN](https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/highlights-public-private-school-systems/), [FR](https://www.quebec.ca/sante/problemes-de-sante/a-z/coronavirus-2019/faits-saillants-covid-ecoles/) (seems to have appeared today)
* this seems to have replaced the PDF that used to be there: [EN](https://cdn-contenu.quebec.ca/cdn-contenu/adm/min/education/publications-adm/covid-19/reseauScolaire_faitsSaillants_ANG.pdf) and [FR](https://cdn-contenu.quebec.ca/cdn-contenu/adm/min/education/publications-adm/covid-19/reseauScolaire_faitsSaillants.pdf)
* List of schools reporting COVID-19 cases: [EN](https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/list-schools-reporting-covid-19-cases/), [FR](https://www.quebec.ca/sante/problemes-de-sante/a-z/coronavirus-2019/liste-des-cas-de-covid-19-dans-les-ecoles/) (seems to have started around Jan 15th)

Do you generally prefer issues or PRs (or both)?

**Comment by jeanpaulrsoucy** [comment]
@mschoettle PRs or both are fine. I'm gradually moving toward a system where other contributors can add everything themselves (will be complete when I fully transition from Google Drive to S3). For now, you can add the new data to datasets.json, if you'd like! I'll take care of the rest later today.

I see the data in the first page is hard-coded, no CSV feeding into it. I've seen this before---starting hard-coded and later being CSV-powered. So best to keep an eye on that one.

**Comment by jeanpaulrsoucy** [comment]
@mschoettle Adding these now! Thanks again for the heads-up.

**Comment by mschoettle** [comment]
Thanks! Will try to do a PR next time again. 

> I see the data in the first page is hard-coded, no CSV feeding into it. I've seen this before---starting hard-coded and later being CSV-powered. So best to keep an eye on that one.

Yes, that seems to happen often. I'll try to keep an eye on it.
