### ISSUE TITLE
Add QC list of schools reporting cases CSV

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#110]
As suspected in #109 the hard-coded data might be replaced with a CSV.

This is now (not sure when it was added) the case for [List of schools reporting COVID-19 cases](https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/list-schools-reporting-covid-19-cases/)/Liste des écoles comptant des cas de COVID-19: 

https://cdn-contenu.quebec.ca/cdn-contenu/education/coronavirus/Liste_ecole_DCOM.csv

**Comment by jeanpaulrsoucy** [comment]
Perfect! Adding it now.
