### ISSUE TITLE
Archive QC English vaccination situation CSV

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#112]
Another English version of the CSVs is not updated anymore:

> Vaccination situation (EN): qc/vaccination-situation-en/situation-vaccination-en.csv

https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/csv/situation-vaccination-en.csv

The French version is now included on the English website.
I could rework #96 to include this and update to your changes but not sure when I will get to it.

**Comment by jeanpaulrsoucy** [comment]
No worries, I can handle it. Thanks for keeping an eye on this. Let me know if you notice any other changes.
