### ISSUE TITLE
Add method of rerunning specific datasets

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaArchive#122]
E.g., If one dataset fails, there should be a way to manually re-run the dataset.

Even better would be if the script could automatically retry failed datasets (some datasets just randomly fail to download and would work if retried).

**Comment by jeanpaulrsoucy** [comment]
This could be achieved by having a secondary script that checks the day's file index and retries any missing files.

**Comment by mschoettle** [comment]
You could try something like this to retry downloading files:

```python
from http import HTTPStatus

MAX_RETRIES = 3

for _ in range(MAX_RETRIES):
    response = requests.get(url)

    if response.status_code != HTTPStatus.OK:
        # could also wait a bit here before continuing 
        continue

    # do something with the response
```

**Comment by jeanpaulrsoucy** [comment]
Closed by https://github.com/ccodwg/Covid19CanadaArchive/commit/45fa9b6304e979d625cb7dd9482e12e31688f70a. Minor modifications may be required in the future.

**Comment by jeanpaulrsoucy** [comment]
Should be able to rerun inactive datasets (i.e., for datasets that need to be captured once but are not part of the nightly update because they are not expected to change).

**Comment by jeanpaulrsoucy** [comment]
Another minor bug:

``
Successful downloads : 1/1
Failed downloads: 0/1

Success: on/toronto-cases/COVID19_cases_2021-08-07_22-22.csv

The following code will rerun failed datasets:
python archiver.py -m prod --uuid
``

**Comment by jeanpaulrsoucy** [comment]
It may be useful to be able to re-run a _range_ of datasets by UUID.

**Comment by jeanpaulrsoucy** [comment]
Print the rerun code to standard error, if possible. (So that it may be easily rerun)

Should the rerun code take into account the options used to run it (beyond the mode)?

**Comment by jeanpaulrsoucy** [comment]
Should also add a --uuid-exclude flag to exclude certain datasets that you *know* will fail but want to remain in datasets.json without being reported as having being failed or automatically retried (e.g., Montreal datasets when running on a non-residential IP address).

**Comment by jeanpaulrsoucy** [comment]
Could add an option to run uuids in random order (e.g., --random-order), which may reduce the number of hits on certain sites in a short period of time. However, it could make it more difficult to rerun large, sequential blocks of uuids manually (i.e., when show-stopping errors occur).

**Comment by jeanpaulrsoucy** [comment]
Should report names of failed dataset at bottom of script as well, for convenience.

**Comment by jeanpaulrsoucy** [comment]
Issue transferred to [archivist](https://github.com/jeanpaulrsoucy/archivist) repository.
