### ISSUE TITLE
Add INSPQ vaccination data (QC)

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#130]
Starting yesterday (March 10th, 2021), INSPQ has a new page on vaccination with more detailed data:

https://www.inspq.qc.ca/covid-19/donnees/vaccination

CSV: https://www.inspq.qc.ca/sites/default/files/covid/donnees/vaccination.csv

The CSV contains historical data. I just downloaded the current version (March 10th): [2021-03-10 vaccination.csv.zip](https://github.com/ccodwg/Covid19CanadaArchive/files/6124398/2021-03-10.vaccination.csv.zip)

**Comment by mschoettle** [comment]
Sorry, I mixed up the dates. Since the data shows March 10th it is probably the version from today.

**Comment by jeanpaulrsoucy** [comment]
Thank you!

**Comment by jeanpaulrsoucy** [comment]
@mschoettle Yup, the hashed values of the zipped file above and the file the script downloaded tonight are identical.

Again, thank you for keeping on top of Quebec data!
