### ISSUE TITLE
Add QC vaccination campagin overview image

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#137]
Seems to be updated weekly.

https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/tableau-suivi-vaccination-groupe-age.jpg

I had opened it this morning and pulled the version dated March 16th out of my browser's cache: 
![IMG_2774](https://user-images.githubusercontent.com/9328433/112205719-73203c80-8beb-11eb-922d-58e06cc17120.jpeg)

**Comment by jeanpaulrsoucy** [comment]
Thanks! Looks like this image first popped up on 2021-03-17, so that's the date I'll use for the archived image.
