### ISSUE TITLE
Add Quebec Regions Vaccination dataset

### ISSUE THREAD

**Issue by andibakti** [ccodwg/Covid19CanadaArchive#146]
Archival data for each region is exists within the pages of the folder 'archive/qc/qc-vaccination-webpage-en/' but that page is now calling a GET request for a csv at [this endpoint](https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/csv/doses-vaccins.csv) which is updated daily.

**Comment by mschoettle** [comment]
That's the French version of the dataset which you can find in `qc/vaccine-doses-admin-by-rss/`.

**Comment by andibakti** [comment]
Oh this is great thanks! (I assume rss stands for somethings with regions then)

**Comment by jeanpaulrsoucy** [comment]
@andibakti

RSS = région sociosanitaire; in English, HR = health region
