### ISSUE TITLE
INSPQ might return old cached dataset

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#148]
Before downloading datasets I verify that there is new data available. I've been having trouble for the last 2 days in that it did not download new data even though there was new data available.

I found out that for the [manual-data.csv](https://www.inspq.qc.ca/sites/default/files/covid/donnees/manual-data.csv) (`qc/covid-data-charts-summary-time-series-hosp-by-age/manual-data.csv`) a cached version might be returned (currently from April 12th). Adding a random string to the query (e.g., `?foobar`) returns the version from today.

They seem to be using Cloudflare and it only happens on one host for me, therefore not sure if it affects you as well but might be worth verifying.

**Comment by jeanpaulrsoucy** [comment]
Is this with a regular web browser or a programmatic tool (e.g., the "requests" module or Python)?

I just checked the MD5 hashes of manual-data.csv from April 5 to April 13. All of them appear to be unique. I also used to generate a "file index" (see [data/data_index.csv](https://github.com/ccodwg/Covid19CanadaArchive/blob/master/data/data_index.csv)) that automatically identified duplicates based on the hash values of the files; I didn't notice any odd patterns in this. Once I fix the indexer.py script again to work with the new server setup (Amazon S3), we can check these things automatically again...

I suspect this would be more likely to be a problem with a conventional web browser than a programmatic tool like we use here (Python's "requests" module) as I don't think there is any cache to speak of...but I am no expert in this.

Something to keep an eye on, for sure, but I haven't identified any issues regarding this yet.

In the mean time, you're free to fetch historical versions from the archive if you need them. :)

**Comment by mschoettle** [comment]
It happens with any client (I used `requests` and `curl`). Digging a bit further it turns out that it only happens for my home IP. For some reason the Cloudflare CDN that they use returns an old version for me. (on the website itself they append a random number to the URLs to prevent this)

Anyway, glad it does not affect your scraping.

**Comment by jeanpaulrsoucy** [comment]
Thanks for the update. That is concerning. I'll keep on an eye on this and once I get the index back up, I will look for any strange duplication patterns in the INSQP datasets. It's possible that this has affected the archive without me noticing. If so, I'll look into mitigation.
