### ISSUE TITLE
Add INSPQ AEFI data

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#157]
Unfortunately missed it when it was introduced. Must have been sometime in April.

https://www.inspq.qc.ca/sites/default/files/covid/donnees/vaccination-mci.csv

Shown on this page: https://www.inspq.qc.ca/covid-19/donnees/vaccination

**Comment by jeanpaulrsoucy** [comment]
Thanks, will add it this afternoon!
