### ISSUE TITLE
Archive some INSPQ variant CSVs

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#158]
The variant data for Rt and projections were updated for the last time yesterday (May 3rd) according to this note on the site:

> Lundi 3 mai 2021 : La proportion de cas de lignée B.1.1.7 parmi les cas positifs au criblage a été ajoutée au tableau 1.1. Le taux de reproduction et les projections spécifiques aux variants (graphiques 2.1 et 2.2) ont quant à eux été mis à jour pour la dernière fois.

https://www.inspq.qc.ca/sites/default/files/covid/donnees/variants-rt.csv
https://www.inspq.qc.ca/sites/default/files/covid/donnees/variants-proj.csv

Also, just before "[3 - Variants confirmés par séquençage](https://www.inspq.qc.ca/covid-19/donnees/variants)" there is a list of presentations that you might be interested in for the archive:

https://www.inspq.qc.ca/sites/default/files/covid/projections/propagation-variants-3mai2021.pdf
https://www.inspq.qc.ca/sites/default/files/covid/projections/propagation-variants-26avril2021.pdf
https://www.inspq.qc.ca/sites/default/files/covid/projections/propagation-variants-19avril2021.pdf
https://www.inspq.qc.ca/sites/default/files/covid/projections/propagation-variants-12avril2021.pdf
https://www.inspq.qc.ca/sites/default/files/covid/projections/propagation-variants-5avril2021.pdf
https://www.inspq.qc.ca/sites/default/files/covid/projections/propagation-variants-inspq-26mars2021.pdf

**Comment by jeanpaulrsoucy** [comment]
Thanks @mschoettle, I've archived the CSVs and downloaded copies of the reports you indicated. I created a separate issue regarding this sort of file, see #162. Would love your input if you have any thoughts about this subject.
