### ISSUE TITLE
Archive QC - Vaccination by age group dashboard

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaArchive#168]
It appears QC - Vaccination by age group is failing as of today.

I believe the file was originally linked on this page: https://www.quebec.ca/sante/problemes-de-sante/a-z/coronavirus-2019/situation-coronavirus-quebec/donnees-sur-la-vaccination-covid-19

This is the direct link to the file: https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/tableau-suivi-vaccination-groupe-age.jpg

@mschoettle Any insight on this file? Has it moved somewhere/transitioned to a different format?

**Comment by mschoettle** [comment]
Yes, it used to be on that page.

Appears to be just removed. I don't see it anywhere else.

The only similar information I saw is here: https://twitter.com/cdube_sante/status/1393167688944521222
Unfortunately, this is sporadic and not available on their website as far as I can tell.
