### ISSUE TITLE
Add MTL vaccination data

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#174]
Noticed today that Sante Montreal added a vaccination data page: https://santemontreal.qc.ca/en/public/coronavirus-covid-19/vaccination/data-vaccination/ (FR: https://santemontreal.qc.ca/population/coronavirus-covid-19/vaccination/donnees/).

It's an ArcGIS dashboard which I am not familiar with. But it should be possible to get the data out somehow. Most interesting is probably the vaccination by age group and vaccination by arrondisement/borough. The other data can already be retrieved on INSPQ's dataset.

The data is updated every Tuesday according to the page.

**Comment by mschoettle** [comment]
Just a quick note that the `VAXparGrpAGE_CSVupload` dataset seems to have been removed. It doesn't throw an error but returns `{"error":{"code":400,"message":"Invalid URL","details":["Invalid URL"]}}`.

The `VAXparGrpAGE_CSVuploadv2` is still there.

**Comment by jeanpaulrsoucy** [comment]
@mschoettle Thanks, will retire it shortly.

I really need to finish #163, which will help me track these things automatically...

**Comment by jeanpaulrsoucy** [comment]
Closed by c1d94c80a995153478be92f42ecf0450378633ef.
