### ISSUE TITLE
file_index.csv is out-of-date

### ISSUE THREAD

**Issue by rstiyer** [ccodwg/Covid19CanadaArchive#175]
The ["Accessing the data" instructions](https://github.com/ccodwg/Covid19CanadaArchive#accessing-the-data) indicate that the [file_index.csv file ](https://data.opencovid.ca.s3.amazonaws.com/archive/file_index.csv) is updated daily, but it has not been updated in 9 days (since 21 May 2021).

Is it possible to bring & keep this file up-to-date? I'm using these data archives via a script which uses `file_index.csv` to determine the file paths from which to extract relevant data.

**Comment by jeanpaulrsoucy** [comment]
Thanks for letting me know. It should be updated now.

I've also updated indexer.py (e581b938d428ace9303c7ff63bbcca6418620101) so that file_index.csv now gets regenerated shortly after the nightly data update. Thus it should be updated nightly ~23:00 ET.

**Comment by rstiyer** [comment]
Thanks for addressing so quickly!

**Comment by rstiyer** [comment]
I'm still seeing this issue. The last entry for BC's `cumulative-case-death-recover-hosp-icu-by-rha` is `COVID19_Cases_by_BC_Health_Authority_2021-05-29_22-02.json`, but there are 2 newer files in the archive.

**Comment by jeanpaulrsoucy** [comment]
Thanks, looks like there must be something wrong with the cron job that's supposed to run indexer.py. I'll get it fixed.

**Comment by jeanpaulrsoucy** [comment]
@rstiyer Should be fixed by 2e188bd1689c4e4c4803548d7bb8e86b32e92865. I've refreshed the index manually, but it should be refreshed automatically around 23:00 ET from now on. Thanks again for letting me know about this.

PS. If you're inclined/able to share, I would be happy to hear more about your use case so I can learn how to better serve users.
