### ISSUE TITLE
Remove duplicate files

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaArchive#183]
This issue was created to centralize various issues around deleting duplicate files.

- [ ] Purge duplicate files from 2021-02-02_15-xx (originally #159)

Due to an error, the archival tool ran mid-day on 2021-02-02 in addition to the usual 10 pm ET nightly update. Thus, there are duplicated files for all the datasets that were in datasets.json at that time. Careful use of the AWS CLI should be able to purge/move these unnecessary files. In some cases, there may actually be two versions of a dataset for a particular date (e.g., due to mid-day updates or corrections). Since February 2, 2021 was a Tuesday, these files are unlikely to have misidentified "corrected" dates (e.g., as they might for datasets that don't normally update on the weekend. Any datasets with 2 unique versions for 2021-02-02 should be carefully dealt with.

- [ ] Purge duplicate files from 2021-07-13_22-xx

As above. Note that one file failed (4 total - can/vaccination-coverage-keypops/vaccination-coverage-keypops.csv) in this earlier update that did not fail (3 total) in the update that was run intentionally (2021-07-23-xx).

- [ ] Purge duplicate files from 2021-07-23_xx-xx

Prod was run twice on this day, since an unreliable Internet connection caused unpredictable failures in the night's update. Thus, most of the files have two versions. The duplicated versions have timestamps of 22-xx or 23-xx, whereas the second run has timestamps of 22-xx or 23-xx.

- [ ] Purge duplicate files from 2021-09-13_xx-xx

As above. Original files have timestamps of 22-xx and the second run files have timestamps of 23-xx.

- [ ] Purge duplicate files from 2021-09-14_xx-xx & 2021-09-15

As above.

- [ ] Purge duplicate files from 2021-09-25

As above.

- [ ] Purge duplicate files from 2021-11-03

As above.

- [ ] Purge duplicate files from 2021-11-12

As above.

- [ ] Purge duplicate files from 2021-11-21

As above.

- [ ] Purge duplicate files from 2021-11-26

As above.

- [ ] Purge duplicate files from 2021-12-30.

From re-running some HTML files with explicit JS after cbd38a25b9f73c811cf98d944476c07b373813e3.

- [ ] Purge duplicate files for retired datasets (#115)
Some files continued to be available following their retirement, causing the archive to fill up with duplicated copies of the final version. The final unique file of an inactive dataset can be determined using data_index.csv. The duplicated files following this final unique file may be safely deleted. No record of their existence need be kept.

A partial list of these files is included below.

- [ ] qc/vaccination-situation-en
- [ ] qc/outbreaks-by-setting-en
- [ ] qc/covid-data-daily-7-days-en
- [ ] qc/cumulative-deaths-by-region-en
- [ ] qc/cases-percentage-by-age-group-en
- [ ] qc/deaths-percentage-by-age-group-en
- [ ] qc/recent-daily-cases-by-region-en
- [ ] qc/schools-highlights
- [ ] qc/schools-highlights-en
- [ ] ns/case-data
- [ ] ns/immunizations
- [ ] ns/immunizations-2
- [ ] other/can/canada-covid-19-school-case-tracker
- [ ] other/qc/covid-ecoles-quebec-school-list
- [ ] bc/school-exposures-island-webpage (empty files)
- [ ] nb/cumulative-vaccination

**Comment by jeanpaulrsoucy** [comment]
Will removing duplicates (not counting duplicates past the final version of the file) affect the calculation of corrected dates?

**Comment by mschoettle** [comment]
QC's `synthese-7jours.csv`, `cas-region.csv` and `cas-region-7jours.csv` are not shown on the [data page](https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec) anymore and therefore will lead to duplicate files as well.

> Since July 12, 2021, the summary table has only published in the balance sheet press release on Mondays and upon return from public holidays, specifically to present the data for the previous days.

**Comment by jeanpaulrsoucy** [comment]
One specific odd case: on/toronto-cases

* etag: a453d3beda4fecd42b55bb29a69d9ae7-4
  * 2021-12-03, 2021-12-06, 2021-12-07
* etag: 81bb42734cd161f06e1d871556dbddb9-2
  * 2021-12-04
* etag: 7457affa44d0c6ba9a0eed99a87d715a-2
  * 2021-12-05

All the files are identical (md5: 2563dbcdbccf86f595034b455d9e0e9b) but the files were added in different ways (manual upload, copy, usual script), creating the different etags.

**Comment by jeanpaulrsoucy** [comment]
Should be solved by #267.
