### ISSUE TITLE
Find missing RPA and CHSLD reports

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaArchive#206]
QC very briefly replaced their RPA and CHSLD reports with a combined report (cc7e84eb-c884-4b8f-ba2a-8fefc49a187c) but appears to have returned to the individual RPA (e1e3a560-814d-4e42-8898-c9bee115e07c) and CHSLD (39ae832e-77b7-494d-9105-0da482050e65) reports. The final combined report is dated September 15 (released September 16). Thus, we have missing reports for at least the following dates:

* September 16
* September 17
* September 18
* September 19

**Comment by mschoettle** [comment]
What's the source location/URL for these datasets?

**Comment by jeanpaulrsoucy** [comment]
https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/etat_situation_rpa.pdf
https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/etat_situation_chsld.pdf

**Comment by jeanpaulrsoucy** [comment]
Merged into #182.
