### ISSUE TITLE
Add Montreal COVID-19 page

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaArchive#58]
https://santemontreal.qc.ca/en/public/coronavirus-covid-19/situation-of-the-coronavirus-covid-19-in-montreal/

**Comment by mschoettle** [comment]
If you're interested in historical scrapes, there are some here: https://github.com/jeremymoreau/covid19mtl/tree/master/app/data/sources (named `data_mtl.html` in each subdirectory)

**Comment by jeanpaulrsoucy** [comment]
@mschoettle Oh, this is great. Thanks for the link!

**Comment by mschoettle** [comment]
I should note that if I am not mistaken the date in the directory name does not represent the date it was downloaded. Rather the date the data shows. There is a shift of one day.

**Comment by jeanpaulrsoucy** [comment]
Merged into #182.
