### ISSUE TITLE
Montreal data - Website aggressively blocks IP addresses

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaArchive#61]
Attempts to download the Montreal data using the server time out. At present, this error kills the whole script. This problem does not seem to occur when the script is run locally.

**Comment by mschoettle** [comment]
I was going to joke that they blocked you, but: I just tried this out on my personal server because it also works for me locally (using another script).

```
>>> import requests
>>> req = requests.get('https://santemontreal.qc.ca/fileadmin/fichiers/Campagnes/coronavirus/situation-montreal/municipal.csv')
```

Result:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='santemontreal.qc.ca', port=443): Max retries exceeded with url: /fileadmin/fichiers/Campagnes/coronavirus/situation-montreal/municipal.csv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbc6947c5e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

The same when I tunnel through my server and make the request in my browser. I should note that this server is located in Europe. Very strange.

**Comment by jeanpaulrsoucy** [comment]
@mschoettle Thanks for looking into this. I just realized they block my local browser too when I am connected to a (Canadian) VPN. It seems their host has gotten a little aggressive about blocking any traffic that looks remotely suspicious.

**Comment by mschoettle** [comment]
Yeah, that seems to be the case.

To avoid any unforeseen errors causing the whole script to crash you could wrap the dl code in a `try ... except ...` block.

**Comment by jeanpaulrsoucy** [comment]
Thanks, I figured I would do something like that with all downloading functions (#53). I have some code re-writes to do anyway as I transition over to an alternate storage system from GitHub (since they might get upset about the size of the repo) (#51).

**Comment by jeanpaulrsoucy** [comment]
We know that the Montreal COVID-19 data website blocks file downloads unless you have a valid-looking useragent string. It also appears to block the IP address of the Heroku server and of my local computer when it is connected to a Canadian VPN. However, it runs fine from my local computer when not connected to a VPN.

It appears to successfully download these data automatically when the script is run from the Heroku server, we will have to use a proxy or similar solution. Ideally, the solution to this issue would be simple to implement, safe and stable (so I don't have to tweak it in the future).

@mschoettle, any ideas?

**Comment by mschoettle** [comment]
Good question. I am still trying to convince Sante Montreal to lift this block (or rather: so they tell their hoster to lift it) but so far it has been unsuccessful.

For the Montreal Dashboard I have been running the scraping from my Raspberry Pi at home to avoid this problem.

Do you have access to a machine that could act as the proxy?

There are two ways that come to mind:
* if you have SSH access to another machine you could create a tunnel and route the traffic through there (as a SOCKS proxy)
* set up a proxy on another machine and route traffic for `santemontreal.qc.ca` through that machine (I've used `haproxy` before to do such a thing)

This would be independent of your archiver script but you could also specifically make requests for Sante Montreal use the proxy in your script.

What do you think?

**Comment by jeanpaulrsoucy** [comment]
@mschoettle I recently moved scraping to a Raspberry Pi, as well.

This closes this issue, for now.
