### ISSUE TITLE
Add Quebec supplementary material

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#99]
There is some supplementary material that the QC government provides that might be of interest to you:

* Dashboard image which contains an overview of the situation in QC including number of people vaccinated from different categories (JPG, [FR](https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/20-210-382W_infographie_sommaire-executif.jpg)) (note: It appeared yesterday, Jan 27th, I downloaded the JPG if you need it)
* Number of active hospitalizations per hospital center (PDF, [FR](https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/tableau-hospitalisations.pdf))
* Vaccination of priority groups (PDF, [EN](https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/20-279-07WA_Previsions_vaccination-anglais.pdf), [FR](https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/20-279-07WF_Previsions_vaccination.pdf)) (I have Jan 5, Jan 11, Jan 14 and Jan 19 if you need them)

**Comment by jeanpaulrsoucy** [comment]
This is great, thank you. Are these all stable URLs (i.e., constantly refreshed with the latest versions of each file)? If so, I'll add them all later today.

I'd love to have your archived files for these three datasets. Please forward them to our group's email account: ccodwg [at] gmail [dot] com. Thanks!

**Comment by jeanpaulrsoucy** [comment]
Btw @mschoettle I'm trying to push #93 through today to refactor the download script, so don't worry about making a pull request to the standard script.

**Comment by mschoettle** [comment]
> Are these all stable URLs (i.e., constantly refreshed with the latest versions of each file)? If so, I'll add them all later today.

I just checked and they all are.

I'll send you the files tonight.

**Comment by jeanpaulrsoucy** [comment]
Datasets have been added, @mschoettle. I will add the archived datasets after you email them, then close out the issue.

**Comment by mschoettle** [comment]
Thanks! I sent the email a few minutes ago.

**Comment by jeanpaulrsoucy** [comment]
Sorry, it got sent to spam. All uploaded! Thanks for keeping tabs on QC data.

**Comment by jeanpaulrsoucy** [comment]
Hi @mschoettle I'm getting an "access denied" error today on the "Vaccination of priority groups" PDFs (FR and EN). Do you know where these files were originally linked from and if there are updated versions/links for them? Thanks!

**Comment by mschoettle** [comment]
It was linked to from the [Vaccination data page](https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec/covid-19-vaccination-data/). It is not linked there anymore so they might have stopped providing it.
